version: '3.8'

services:

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - './api:/app:rw'
      - '/app/node_modules/'

  # db:


  # Uyility containers
  api-npm:
    image: node:20.16.0-alpine
    working_dir: /app
    entrypoint: ['npm']
    volumes:
      - './api:/app'
  api-npx:
    image: node:20.16.0-alpine
    working_dir: /app
    entrypoint: ['npx']
    volumes:
      - './api:/app'