version: '3.8'

services:

  api:
    container_name: 'api-server'
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - './:/app:rw'
      - '/app/node_modules/'
    networks:
      - api-network

  db:
    container_name: 'api-database'
    image: 'postgres:16-alpine'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db-volume:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - api-network
    restart: unless-stopped


  # Utility containers
  # For example: docker-compose run --rm api-npm i -D @types/express
  api-npm:
    image: node:20.16.0-alpine
    working_dir: /app
    entrypoint: ['npm']
    volumes:
      - './:/app'
  api-npx:
    image: node:20.16.0-alpine
    working_dir: /app
    entrypoint: ['npx']
    volumes:
      - './:/app'



volumes:
  db-volume:
    driver: local

networks:
  api-network:
    name: api-network